name: Build Ignition from Butane

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Butane to Ignition
        run: |
          podman run --rm \
            -v "${{ github.workspace }}:/workspace" \
            quay.io/coreos/butane:release \
            --pretty \
            --strict \
            -d /workspace \
            -o /workspace/config.ign \
            /workspace/config.bu

      - name: Version output files 
        run: | 
          TAG="${GITHUB_REF_NAME}"
          DATE=$(date +'%Y-%m-%d')

      - name: Upload Ignition artifact 
        uses: actions/upload-artifact@v4
        with:
          name: ignition-${TAG}
          path: |
            config.ign

      - name: Create GitHub Release (immutable)
        uses: softprops/action-gh-release@v2 
        with: 
          name: config.ign
          tag_name: ${{ github.ref_name }} 
          generate_release_notes: false
          make_latest: true 
          fail_on_unmatched_files: true 
          files: | 
            config.ign 
